# Deployment for Web App 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-web-app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-web-app-1
  template:
    metadata:
      labels:
        app: httpd-web-app-1
    spec:
      containers:
      - name: httpd-container
        image: httpd:latest
        ports:
        - containerPort: 80
---
# ClusterIP Service for Web App 1
apiVersion: v1
kind: Service
metadata:
  name: httpd-web-app-1-svc
spec:
  selector:
    app: httpd-web-app-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpd-web-app-1-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  # Specify the Ingress class
  rules:
  - host: webapp1.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpd-web-app-1-svc
            port:
              number: 80
