apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-httpd-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-httpd
  updatePolicy:
    updateMode: "Auto"  # Can be "Off", "Initial", or "Auto"
